export default {
  category: [
    {
      id: '1',
      category: 'painter',
    },
    {
      id: '2',
      category: 'plumber',
    },
    {
      id: '3',
      category: 'electrician',
    },
    {
      id: '4',
      category: 'carpenter',
    },
  ],
  Sheet2: [
    {
      id: '1',
      categoyrid: '1',
      professional: 'painter',
      name: 'Jacob',
      rating: '4.1',
      project: '5-complete',
      number: '(888) 450-9675',
      images: require('../assets/images/1.png'),
      about:
        'College Works Painting provides valuable, practical and life-changing business experience for college and university students who have shown potential for success, while also providing high quality residential painting services for people interested in opening opportunities for our next generation of business leaders. ',
    },
    {
      id: '2',
      categoyrid: '1',
      professional: 'painter',
      name: 'Savanna',
      rating: '4.3',
      project: '7-complete',
      number: '(239) 273-4556',
      images: require('../assets/images/2.png'),
      about:
        'Ceiling Painting, Color Consulting, Deck Staining, Decorative Painting, Door Painting, Drywall Repair, Exterior Painting, Faux Painting, Garage Floor Coating, Garage Floor Refinishing, Interior Painting, Paint Removal, Plaster Repair, Popcorn Ceiling Removal, Texture Painting, Wallpaper Removal, Screen cage painting',
    },
    {
      id: '3',
      categoyrid: '1',
      professional: 'painter',
      name: 'Danny Olivera\r',
      rating: '4.5',
      project: '8-complete',
      number: '(615) 595-0207',
      images: require('../assets/images/3.png'),
      about:
        ' we’ve worked hard over the last three decades to build our reputation as one of the Nashville area’s most trusted painting companies. We work hard to make sure the job gets done the right way,',
    },
    {
      id: '4',
      categoyrid: '1',
      professional: 'painter',
      name: 'Jonathan ',
      rating: '4.3',
      project: '4-complete',
      number: '(858) 586-7751',
      images: require('../assets/images/4.png'),
      about:
        'Brad Stoner Painting is a San Diego-based painting company specializing in both interior and exterior painting projects. We use only the finest paints and materials to complete our projects and strive to offer the best all-around service possible',
    },
    {
      id: '5',
      categoyrid: '1',
      professional: 'painter',
      name: 'Jmo Da',
      rating: '3.8',
      project: '9-complete',
      number: '(720) 331-9735',
      images: require('../assets/images/5.png'),
      about:
        "set the standard for house painters in Colorado by dedicating ourselves to serving clients. Vivax is a trusted home improvement contractor and unlike many other companies, don't accept payment or deposits until you",
    },
    {
      id: '6',
      categoyrid: '2',
      professional: 'plumber',
      name: 'Manny De',
      rating: '4.2',
      project: '10-complete',
      number: '(864) 256-4120',
      images: require('../assets/images/6.png'),
      about:
        'At All Clear Plumbing, we believe that every family deserves the dignity of quality plumbing at a fair price. We want every customer to feel like we’re taking care of their home like we would take care of our own',
    },
    {
      id: '7',
      categoyrid: '2',
      professional: 'plumber',
      name: 'Ciarra',
      rating: '3.8',
      project: '5-complete',
      number: '(505) 431-4025',
      images: require('../assets/images/7.png'),
      about:
        'our commitment to you is to provide excellent plumbing service in Albuquerque, at affordable rates, and take the time to clean up before we leave. As consummate professionals, we take pride in everything we do. We cater to all of your plumbing or remodeling need',
    },
    {
      id: '8',
      categoyrid: '2',
      professional: 'plumber',
      name: 'justin',
      rating: '3.5',
      project: '12-complete',
      number: '(508) 306-4635',
      images: require('../assets/images/8.png'),
      about:
        "When it comes to great service for your home or business, it doesn't get better than the professionalism and dedication of Rodenhiser.  It's an unsurpassed level of service built on a promise that ensures you get the very best",
    },
    {
      id: '9',
      categoyrid: '2',
      professional: 'plumber',
      name: 'Savannah Roark',
      rating: '3.9',
      project: '14-complete',
      number: '(208) 877-2180',
      images: require('../assets/images/9.png'),
      about:
        'Einstein Plumbing Boise is the best choice for any and all Boise plumbing services.  No other Boise plumber can compete with Keith’s level of dedication, expertise, or technology.',
    },
    {
      id: '10',
      categoyrid: '2',
      professional: 'plumber',
      name: 'farnk',
      rating: '4.5',
      project: '8-complete',
      number: '(844) 532-5244',
      images: require('../assets/images/10.png'),
      about:
        'Reliable services for residential, commercial and emergency plumbing services are offered on all days of the week with no additional charged for overtime work',
    },
    {
      id: '11',
      categoyrid: '3',
      professional: 'electrician',
      name: 'HENRY',
      rating: '4.5',
      project: '5-complete',
      number: '(262) 442-2636',
      images: require('../assets/images/11.png'),
      about:
        'Antenna Installation, Ceiling Fan Installation, Ceiling Fan Repair, Circuit Breaker Installation & Repair, Deck Lighting Installation, Electrical Inspection, Electrical Installation, Electrical Outlet & Light Switch Installation, Electrical Repair, Elevator Repair, Exhaust Fan Installation',
    },
    {
      id: '12',
      categoyrid: '3',
      professional: 'electrician',
      name: 'Lou Cutz',
      rating: '3.7',
      project: '7-complete',
      number: '(253) 358-3239',
      images: require('../assets/images/12.png'),
      about:
        'Artondale, Burley, Canterwood, Fox Island, Gig Harbor, Key Center, Olalla, Port Orchard, Purdy, Rosedale, Tacoma, University Place, Wauna, Wollochet',
    },
    {
      id: '13',
      categoyrid: '3',
      professional: 'electrician',
      name: 'Allseasonz',
      rating: '3.5',
      project: '8-complete',
      number: '(213) 335-7385',
      images: require('../assets/images/13.png'),
      about:
        'We specialize in all types of electrical jobs. Residential Electrical Repair Fire Alarm Installation GFI Electrical Outlets Installation Chandelier Installation Aluminum Wire Replacement Electric Panel Upgrades EV/Tesla Charger Installation House Rewiring Wiring Installation Smoke Detector Installation Lighting',
    },
    {
      id: '14',
      categoyrid: '3',
      professional: 'electrician',
      name: 'MACHO',
      rating: '3.6',
      project: '4-complete',
      number: '(763) 220-2861',
      images: require('../assets/images/14.png'),
      about:
        'We believe you deserve a safe and reliable home. Our licensed electricians help you get the job done right the first time with outstanding customer service from the Twin Cities top rated electrical company.',
    },
    {
      id: '15',
      categoyrid: '3',
      professional: 'electrician',
      name: 'Jay',
      rating: '4.7',
      project: '9-complete',
      number: '(410) 893-7210',
      images: require('../assets/images/15.png'),
      about:
        'We can proudly state that, due to our relentless drive to deliver superior customer satisfaction, we have an outstanding referral rating with resident homeowners in Harford County. In fact, some of our clients have actually referred Helms Electric to their own children.',
    },
    {
      id: '16',
      categoyrid: '4',
      professional: 'carpenter',
      name: 'Jay Rozay',
      rating: '3.4',
      project: '10-complete',
      number: '(503) 741-2758',
      images: require('../assets/images/16.png'),
      about:
        'Specializing in stairways he installs treads, risers, newels, rails and balusters. Also installing wainscot, trim, doors, baseboards, and crown molding. Michael with GoManGo Enterprises is a full service master craftsman that is ready to create unique and functional works of beauty for your home',
    },
    {
      id: '17',
      categoyrid: '4',
      professional: 'carpenter',
      name: 'Michael',
      rating: '3.8',
      project: '5-complete',
      number: '(609) 263-2793',
      images: require('../assets/images/17.png'),
      about:
        'We have become renowned as the leading South Jersey custom finish carpentry company and earned a reputation as a provider of the highest quality custom woodwork and customer service.',
    },
    {
      id: '18',
      categoyrid: '4',
      professional: 'carpenter',
      name: 'James',
      rating: '3.5',
      project: '12-complete',
      number: '(715) 602-4160',
      images: require('../assets/images/18.png'),
      about:
        ' Over the years our services have grown from fine finish custom carpentry to all phases of building construction. The demands of high quality craftsmanship as finish carpenters has driven Nordic Builders to apply that same quality into every project',
    },
    {
      id: '19',
      categoyrid: '4',
      professional: 'carpenter',
      name: 'John Rourke',
      rating: '4.2',
      project: '14-complete',
      number: '(904) 201-8244',
      images: require('../assets/images/19.png'),
      about:
        'll interior woodwork including mantles, crown molding, wainscoting, built-in cabinetry walk-in closets and interior doors.',
    },
    {
      id: '20',
      categoyrid: '4',
      professional: 'carpenter',
      name: 'William',
      rating: '4.1',
      project: '8-complete',
      number: '(248) 396-9151',
      images: require('../assets/images/20.png'),
      about:
        'We are a home improvement company specializing in bathrooms, kitchens, and basements. We take a lot of pride in not only the quality of work we produce but also in the experience we provide',
    },
  ],
};
